const TODOLODDING = "TODOERROR";
const FETCHTODO = "FETCHTODO";
const TODOERROR = "TODOERROR";
const ADDTASK = "ADDTASK";
const DELETETASK = "DELETETASK";
const COMPLETETASK = "COMPLETETASK";
const SEARCHTODOFETCH = "SEARCHTODOFEATCH";
export {
  TODOERROR,
  TODOLODDING,
  FETCHTODO,
  ADDTASK,
  DELETETASK,
  COMPLETETASK,
  SEARCHTODOFETCH,
};
