const REGISTRATIONSUCCESS = "REGISTRATIONSUCCESS";
const LOADING = "LOADING";
const ERROR = "ERROR";
// const RESET = "RESET";
const LOGINSUCCESS = "LOGINSUCCESS";
const LOGOUT = "LOGOUT";
const ERRORTOOGLE = "ERRORTOOGLE";
export {
  REGISTRATIONSUCCESS,
  LOADING,
  ERROR,
  LOGINSUCCESS,
  LOGOUT,
  ERRORTOOGLE,
};
